// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5MFjJUDBUV4191V8xrPw8NRTjMN198uI',
    appId: '1:353914637980:web:0cfd727ffdf73714cce759',
    messagingSenderId: '353914637980',
    projectId: 'esp8266-values-d231f',
    authDomain: 'esp8266-values-d231f.firebaseapp.com',
    databaseURL: 'https://esp8266-values-d231f-default-rtdb.firebaseio.com',
    storageBucket: 'esp8266-values-d231f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBKs3vJc16c5cWD_fFi1y5ZGF0fbGwmP4',
    appId: '1:353914637980:android:8e05ed06a01651c1cce759',
    messagingSenderId: '353914637980',
    projectId: 'esp8266-values-d231f',
    databaseURL: 'https://esp8266-values-d231f-default-rtdb.firebaseio.com',
    storageBucket: 'esp8266-values-d231f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUDDXw7xyLJwfsqxdWh5IbHcBj5fHiJfE',
    appId: '1:353914637980:ios:d5637d6a0c642036cce759',
    messagingSenderId: '353914637980',
    projectId: 'esp8266-values-d231f',
    databaseURL: 'https://esp8266-values-d231f-default-rtdb.firebaseio.com',
    storageBucket: 'esp8266-values-d231f.appspot.com',
    iosBundleId: 'com.example.security',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUDDXw7xyLJwfsqxdWh5IbHcBj5fHiJfE',
    appId: '1:353914637980:ios:a29421ca6bdf2484cce759',
    messagingSenderId: '353914637980',
    projectId: 'esp8266-values-d231f',
    databaseURL: 'https://esp8266-values-d231f-default-rtdb.firebaseio.com',
    storageBucket: 'esp8266-values-d231f.appspot.com',
    iosBundleId: 'com.example.security.RunnerTests',
  );
}
